### PR TITLE
notifications: fix duplicate notification issue

### LINKED ISSUE #125: Double Desktop Notifications
**Describe the bug, optionally with screenshots**
Any time I get a message I get 2 desktop notifications. One with the header `Landscape: Groups` and one with the header `Landscape: Talk`. This is for every message and, because it's from Landscape, I can be sitting in the talk window watching the messages and I still get 2 alerts for every message in the channel.

**To Reproduce**
1. Have Landscape open but not active
2. Receive message in a channel with notifications turned out
3. See 2 desktop alerts.

**Expected behavior**
One notification if I'm not in Landscape, Groups, or Talk. One notification otherwise.

**Additional context:**
- Ship type: Moon
- Instance type: self-hosted with CLI
- OS/browser: Manjaro/Brave

### PR DESCRIPTION
**Pull request by patosullivan**
fixes #125 

I wasn't able to reproduce the exact issue in #125, but I think this was actually what the user was seeing.

We were firing off a test notification each time the count or unreadNotifications changed, along with the real notification itself.

We also weren't properly including notification content (DMs or mentions would just show that you got a DM or a mention, but not the content of the message). This fixes that.

### CODE REVIEW

File: ui/src/logic/utils.ts [hunk 1]
```diff
@@ -21,10 +24,5 @@ export const makeBrowserNotification = (bin: Bin) => {
 
 export function isNewNotificationSupported() {
   if (!window.Notification || !Notification.requestPermission) return false;
-  try {
-    new Notification('');
-  } catch (e: any) {
-    if (e.name == 'TypeError') return false;
-  }
```
Comment (arthyn) [inline ui/src/logic/utils.ts:28]: this was the fix from #123 probably should leave in

**Review by arthyn — CHANGES_REQUESTED** [review]

File: ui/src/logic/utils.ts (hunk 1 above)
Comment (patosullivan) [reply ui/src/logic/utils.ts:28]: This is what is producing duplicate notifications on desktop. Won't the try catch in the makeBrowserNotification function catch this?

**Review by arthyn — APPROVED** [review]
lgtm
